### ISSUE TITLE
Authentication check result is ignored when routing to a function

### ISSUE THREAD

**Issue by daehlith** [felipeleusin/hapi-negotiator#4]
In a small example project that I am using to learn I've got the following route set up:

```
server.route({
	method: 'GET',
	path: '/',
	handler: defaultHandler,
	config: {
		auth: {
			strategy: 'token'
		},
		plugins: {
			'hapi-negotiator': {
				mediaTypes: {
					'application/vnd.jivaro.hello.v1+json': helloV1,
					'application/vnd.jivaro.hello.v2+json': helloV2
				}
			}
		}
	}
});
```
When I request this route without any accept header - e.g. with `curl -i http://localhost:5678` - it falls back to the default handler and yields the expected result:
```
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Bearer
content-type: application/json; charset=utf-8
cache-control: no-cache
content-length: 76
Date: Tue, 27 Jan 2015 16:54:50 GMT
Connection: keep-alive

{"statusCode":401,"error":"Unauthorized","message":"Missing authentication"}
```
However, when I request with a specific accept header - f.e. with `curl -H "Accept: application/vnd.jivaro.hello.v1+json" -i http://localhost:5678/` - then the auth check is circumvented:
```
HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
cache-control: no-cache
content-length: 46
accept-ranges: bytes
Date: Tue, 27 Jan 2015 16:58:45 GMT
Connection: keep-alive

{"text":"Hello Version 1!","credentials":null}
```

A quick fix that resolved this issue for me was adding the following code right at the beginning of the onPreResponse handler:
```
	if (request.response.output) {
		var statusCode = request.response.output.statusCode;
		if (statusCode >= 400) {
			return reply.continue();
		}
	}
```
Now performing `curl -H "Accept: application/vnd.jivaro.hello.v1+json" -i http://localhost:5678/` yields the expected result:
```
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Bearer
content-type: application/json; charset=utf-8
cache-control: no-cache
content-length: 76
Date: Tue, 27 Jan 2015 17:11:52 GMT
Connection: keep-alive

{"statusCode":401,"error":"Unauthorized","message":"Missing authentication"}
```

**Comment by daehlith** [comment]
I've updated the OP with code that is working, can create another pull request later on but I've got to run right now.

**Comment by felipeleusin** [comment]
I'll look into it later tonight.... I think this is ok but we have to be sure this doesn't break anything as you mentioned in the PR.

**Comment by daehlith** [comment]
I've created a new pull request including a unit test.

**Comment by felipeleusin** [comment]
Ok. I'll look into it. Thanks for the help!

Em qua, 28 de jan de 2015 10:30, Thomas Dähling <notifications@github.com>
escreveu:

**Comment by gig-github** [comment]
Another solution that might work (I've tested it with my own plugin and it looks good): instead of onPreResponse use onPostHandler.

Here's what I observed and read in the Hapi reference: when you add an error response during a request lifecycle then the lifecycle is aborted, skipping the rest of the events, all they way to onPreResponse. So onPreResponse always gets emitted, it seems to be for response manipulation for ALL requests that come in, regardless of how their lifecycle turns out. onPostHandler on the other hand maintains the default handler functionality of the hapi-negotiator but gets skipped over if previous event handlers want to reply with an error.

This way you don't have to worry about whether there has been an error, in your code you can assume everything is fine and dandy.

**Comment by felipeleusin** [comment]
Yeah,
That was what I wanted to check... I think this is a better solution. What do you think @daehlith ?

**Comment by daehlith** [comment]
If switching to `onPostHandler` has no other side-effects then it's certainly a better solution than having an explicit if-statement within the handler itself. And at least all the tests are passing at 100% coverage with `onPostHandler` instead of `onPreResponse`.
I'd say let's go with `onPostHandler` then.

**Comment by felipeleusin** [comment]
Ok. Just checked it. Good job!
